# Turns the GUI's index.html into a C++ translation unit exposing it as a
# string, so `abp gui` needs no asset files at runtime.
#
# Invoked in script mode: cmake -DINPUT=... -DOUTPUT=... -P EmbedWebUi.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "EmbedWebUi.cmake requires -DINPUT=<html> -DOUTPUT=<cpp>")
endif()

file(READ "${INPUT}" ABP_WEBUI_HTML)

# The generated file wraps the HTML in raw string literals, which is only
# safe as long as the HTML never contains the closing delimiter.
if(ABP_WEBUI_HTML MATCHES "\\)ABPHTML\"")
    message(FATAL_ERROR "${INPUT} contains the raw string delimiter )ABPHTML\" and cannot be embedded.")
endif()

# Compilers are only required to accept string literals up to 64 KiB (clang
# enforces it under -Wpedantic), so the page is emitted as several literals
# joined at runtime. Chunks end at a newline, never inside a UTF-8 sequence.
set(ABP_CHUNK_TARGET 30000)
set(ABP_CHUNKS "")
string(LENGTH "${ABP_WEBUI_HTML}" ABP_REMAINING)
while(ABP_REMAINING GREATER 0)
    if(ABP_REMAINING GREATER ABP_CHUNK_TARGET)
        string(SUBSTRING "${ABP_WEBUI_HTML}" ${ABP_CHUNK_TARGET} -1 ABP_TAIL)
        string(FIND "${ABP_TAIL}" "\n" ABP_NEWLINE)
        if(ABP_NEWLINE EQUAL -1)
            set(ABP_CUT ${ABP_REMAINING})
        else()
            math(EXPR ABP_CUT "${ABP_CHUNK_TARGET} + ${ABP_NEWLINE} + 1")
        endif()
    else()
        set(ABP_CUT ${ABP_REMAINING})
    endif()
    string(SUBSTRING "${ABP_WEBUI_HTML}" 0 ${ABP_CUT} ABP_CHUNK)
    string(APPEND ABP_CHUNKS "    R\"ABPHTML(${ABP_CHUNK})ABPHTML\",\n")
    string(SUBSTRING "${ABP_WEBUI_HTML}" ${ABP_CUT} -1 ABP_WEBUI_HTML)
    string(LENGTH "${ABP_WEBUI_HTML}" ABP_REMAINING)
endwhile()

get_filename_component(ABP_WEBUI_OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${ABP_WEBUI_OUTPUT_DIR}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedWebUi.cmake from src/gui/web/index.html -- do not edit.
#include \"abp/WebUi.h\"

#include <string>

namespace abp::webui {
namespace {

const char* const kChunks[] = {
${ABP_CHUNKS}};

} // namespace

const char* indexHtml() {
    static const std::string page = [] {
        std::string joined;
        for (const char* chunk : kChunks) joined += chunk;
        return joined;
    }();
    return page.c_str();
}

} // namespace abp::webui
")
