# Turns the GUI's index.html into a C++ translation unit exposing it as a
# string literal, so `abp gui` needs no asset files at runtime.
#
# Invoked in script mode: cmake -DINPUT=... -DOUTPUT=... -P EmbedWebUi.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "EmbedWebUi.cmake requires -DINPUT=<html> -DOUTPUT=<cpp>")
endif()

file(READ "${INPUT}" ABP_WEBUI_HTML)

# The generated file wraps the HTML in a raw string literal, which is only
# safe as long as the HTML never contains the closing delimiter.
if(ABP_WEBUI_HTML MATCHES "\\)ABPHTML\"")
    message(FATAL_ERROR "${INPUT} contains the raw string delimiter )ABPHTML\" and cannot be embedded.")
endif()

get_filename_component(ABP_WEBUI_OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${ABP_WEBUI_OUTPUT_DIR}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedWebUi.cmake from src/gui/web/index.html -- do not edit.
#include \"abp/WebUi.h\"

namespace abp::webui {

const char* indexHtml() {
    return R\"ABPHTML(${ABP_WEBUI_HTML})ABPHTML\";
}

} // namespace abp::webui
")
